name: Build and Deploy

on:
  push:
    paths:
      - 'src/**'
      - 'vite.config.js'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/build-and-deploy.yml'
      - 'tailwind.config.js'
      - 'postcss.config.js'
      - 'index.html'
    branches:
      - main


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Vite project
        run: npm run build

      - name: Cache dist folder
        uses: actions/cache@v2
        with:
          path: dist
          key: dist-${{ github.run_id }}

      - name: Deploy dist folder to release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
          git stash push dist
          git checkout --orphan release
          git rm -rf .
          git clean -fdx
          
          git stash apply --index
          cp -r dist/* .
          
          git add .
          git commit -m "Release: Build $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f origin release
